version: '3'
services:
  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    build: ./flask-server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis  # Redis hostname beállítása
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
