version: '3'
services:
  frontend:
    build: ./client
    ports:
      - "3000:80" # 3000-es port a fejlesztői React szerverhez
    volumes:
      - ./client # Lokális fájlok megosztása a konténerrel
      - /client/node_modules # A node_modules mappa kizárása, hogy a lokális gépeden lévő fájlok ne ütközzenek a konténerben lévőkkel
    environment:
      - CHOKIDAR_USEPOLLING=true # Ez a változó szükséges lehet, hogy a fájlváltozásokat kövesse a Docker
    depends_on:
      - backend
  backend:
    build: ./flask-server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
networks:
  default:
    external:
      name: docker_internal
